In [1]:
#!/usr/bin/env python3

import rospy
import numpy as np
import math
from utils import dvrk_devel_utils as dvrk_utils

ModuleNotFoundError: No module named 'rospy'

In [2]:
# print with node id
def print_id(message):
    print('%s -> %s' % (rospy.get_caller_id(), message))

In [4]:
app = dvrk_utils.DVRK_CTRL('ECM', 0.01)

/dvrk_ECM_411678_1701812130889 -> configuring dvrk_arm_test for ECM
Destructing Class DVRK_CTRL...


In [15]:
app.home_zero_position(5)

/dvrk_ECM_411678_1701812130889 -> starting enable
/dvrk_ECM_411678_1701812130889 -> starting home
/dvrk_ECM_411678_1701812130889 -> move to zero position
/dvrk_ECM_411678_1701812130889 -> moving to zero position complete


In [19]:
goal_jp = np.copy(app.get_jp())
for i in range(len(goal_jp)):
    if i == 2:
        goal_jp[i] += math.radians(2)
    else:
        goal_jp[i] += math.radians(10)

In [20]:
goal_jp

array([0.17475155, 0.17490194, 0.0650753 , 0.17472067])

In [21]:
app.run_arm_servo_jp(goal_jp, 5)

In [ ]:
app = example_application()
app.configure('PSM1', 0.01)
app.home_zero_position()
app.arm.jaw.open(angle = math.radians(0)).wait()

In [38]:
app = dvrk_utils.DVRK_CTRL('PSM2', 0.01)
app.home_zero_position(5)
app.arm.jaw.open(angle = math.radians(0)).wait()

/dvrk_arm_test_139681_1693493410002 -> configuring dvrk_arm_test for PSM2
Destructing Class DVRK_CTRL...
/dvrk_arm_test_139681_1693493410002 -> starting enable
/dvrk_arm_test_139681_1693493410002 -> starting home
/dvrk_arm_test_139681_1693493410002 -> move to zero position
/dvrk_arm_test_139681_1693493410002 -> moving to zero position complete


False

In [ ]:
app.arm.jaw.open(angle = math.radians(0)).wait()

In [ ]:
app.arm.jaw.close().wait()

In [ ]:
# Set ECM to initial position (for PSM1, PSM2 Aruco Calibration)
app = example_application()
app.configure('ECM', 0.01)
goal = numpy.copy(app.arm.setpoint_jp())
goal[1] = math.radians(30)
goal[2] = 0.23
goal[3] = math.radians(0)
app.run_servo_jp(goal,duration=5)

In [ ]:
# Set ECM to initial position (for ECM Aruco Calibration)
app = example_application()
app.configure('ECM', 0.01)
goal = numpy.copy(app.arm.setpoint_jp())
goal[0] = math.radians(0)
goal[1] = math.radians(0)
goal[2] = 0.15
goal[3] = math.radians(0)
app.run_servo_jp(goal,duration=5)

In [ ]:
app.arm.setpoint_jp()

In [ ]:
# Set ECM to initial position (for Procedure)
app = example_application()
app.configure('ECM', 0.01)
goal = numpy.zeros_like(app.arm.setpoint_jp())
goal[0] = math.radians(0)
goal[1] = math.radians(-0)
goal[2] = 0.03
goal[3] = math.radians(-0)
app.run_servo_jp(goal,duration=6)

In [15]:
# Set PSMs to initial position (for Procedure)
app = dvrk_utils.DVRK_CTRL('PSM1', 0.01)
goal = app.arm.setpoint_jp()
goal[0] = math.radians(5)
goal[1] = math.radians(-20)
goal[2] = 0.03
goal[3] = math.radians(-120)
goal[4] = math.radians(20)
goal[5] = math.radians(0)
app.run_servo_jp(goal,duration=10)
# app.arm.jaw.close().wait()

/dvrk_arm_test_105960_1696873784322 -> configuring dvrk_arm_test for PSM1
Destructing Class DVRK_CTRL...


In [22]:
# Set PSMs to initial position (for Procedure)
app = dvrk_utils.DVRK_CTRL('PSM2', 0.01)
goal = app.arm.setpoint_jp()
goal[0] = math.radians(-15)
goal[1] = math.radians(-45)
goal[2] = 0.03
goal[3] = math.radians(-0)
goal[4] = math.radians(0)
goal[5] = math.radians(0)
app.run_servo_jp(goal,duration=5)
# app.arm.jaw.open(angle = math.radians(0)).wait()

/dvrk_arm_test_139681_1693493410002 -> configuring dvrk_arm_test for PSM2
Destructing Class DVRK_CTRL...


In [5]:
app.get_local_cp()

array([[-0.9337379 ,  0.03613891, -0.35612852, -0.73424405],
       [ 0.24190478, -0.66962012, -0.70220437,  0.05843845],
       [-0.26384772, -0.74182402,  0.61650751, -0.00655592],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [6]:
# Set PSMs to initial position (for Procedure)
app = dvrk_utils.DVRK_CTRL('PSM2', 0.01)
goal = app.arm.setpoint_jp()
goal[0] = math.radians(12)
goal[1] = math.radians(18)
goal[2] = 0.10
goal[3] = math.radians(-0)
goal[4] = math.radians(0)
goal[5] = math.radians(0)
app.run_servo_jp(goal,duration=5)
# app.arm.jaw.open(angle = math.radians(0)).wait()

/dvrk_arm_test_19730_1693333613612 -> configuring dvrk_arm_test for PSM2
/dvrk_arm_test_19730_1693333613612 -> Destructing Class DVRK_CTRL...


In [7]:
app.get_local_cp()

array([[-0.92705437, -0.04044636,  0.37273889, -0.6615583 ],
       [-0.37040243,  0.25278378, -0.8938134 , -0.03126025],
       [-0.05807084, -0.96667702, -0.24932574, -0.08760494],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
# Set PSMs to initial position (for Procedure)
app = example_application()
app.configure('MTML', 0.01)
goal = app.arm.setpoint_jp()
goal[0] = math.radians(0)
goal[1] = math.radians(-0)
goal[2] = 0.0
goal[3] = math.radians(-0)
goal[4] = math.radians(0)
goal[5] = math.radians(0)
app.run_servo_jp(goal,duration=5)

In [ ]:
app = example_application()
app.configure('MTMR', 0.01)
goal = app.arm.setpoint_jp()
goal[0] = math.radians(0)
goal[1] = math.radians(-0)
goal[2] = 0.0
goal[3] = math.radians(-0)
goal[4] = math.radians(0)
goal[5] = math.radians(0)
app.run_servo_jp(goal,duration=5)

In [ ]:
while not rospy.is_shutdown():
    goal = numpy.zeros_like(app.arm.setpoint_jp())
    goal[5] = math.radians(random.randint(-60,60))
    app.run_servo_jp(goal)

In [ ]:
goal = numpy.copy(app.arm.setpoint_jp())
goal[5] = math.radians(-80)
app.run_servo_jp(goal)

In [ ]:
goals = numpy.array([math.radians(90),math.radians(-85),
                     math.radians(33),math.radians(-50),
                                    0,            0.240,
                     math.radians(55),math.radians(-55),
                     math.radians(30),math.radians(-25),
                     math.radians(80),math.radians(-80)])

In [ ]:
numpy.floor_divide(5,2)

In [ ]:
from sensor_msgs.msg import JointState
psm1_js = rospy.wait_for_message("/PSM1/setpoint_js",JointState)

In [ ]:
numpy.array(psm1_js.position).shape